#!/usr/bin/ruby

def changelog_and_version_paths()
  `git ls-files`
    .lines(chomp: true)
    .select {|path| path =~ %r|/VERSION|}
    .map    {|path| [path.sub(%r|/VERSION$|, '/ChangeLog.md'), path]}
    .select {|paths| paths.all? {|path| File.exist? path}}
end

def changelog_latest_version(path)
  File.read(path)[/^\s*##\s*\[v(\d[\d\.]+\d)\]\s*-\s*\d{4}-\d{2}-\d{2}\s*$/, 1]
end

def current_version(path)
  File.read(path)[/[\d\.]+/]
end

changelog_and_version_paths.each do |changelog, version|
  ver = changelog_latest_version changelog
  if ver && ver != current_version(version)
    File.write version, ver
    `git add #{version}`
  end
end
