name: Subtree Push

on:
  push:
    branches: [master]

jobs:
  subtree-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: ruby 3.1
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1

      - name: subtree-push
        run: rake subtree:push
